version: "3.8"

services:
  localstack-clear-arch:
    container_name: localstack-clean-arch
    build:
      context: ./localstack
      dockerfile: Dockerfile
    ports:
      - '4566:4566'
    environment:
      SERVICES: dynamodb
      AWS_DEFAULT_REGION: sa-east-1
      AWS_ACCESS_KEY_ID: 123
      AWS_SECRET_ACCESS_KEY: 123
      EDGE_PORT: 4566
      AWS_DEFAULT_OUTPUT: json
      DEBUG: 1
      USE_SSL: 0
    volumes:
      - "./localstack/aws:/root/.aws"
      - "./localstack:/var/lib/localstack"
      - "./localstack:/docker-entrypoint-initaws.d"